
POST http://localhost:3000/api/auth/login 
Content-Type: application/json

{
    "userName": "JohnA",
    "email" : "ab@ab.com", 
    "password" : "azerty4055"
}
###
POST http://localhost:3000/api/auth/login 
Content-Type: application/json

{
    "userName": "John",
    "email" : "john@gmail.com", 
    "password" : "azerty4055"
}
###
POST http://localhost:3000/api/auth/signup 
Content-Type: application/json

{
    "userName": "Leon",
    "email" : "Leon@gmail.com", 
    "password" : "azerty4055"
}
###
DELETE http://localhost:3000/api/users/44
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE2LCJpYXQiOjE2Mjc0NzUzMTAsImV4cCI6MTYyNzU2MTcxMH0.SI-Xn83lezSiOH8ZbxLHi_xP-lyLj60ELOVTN1kMNFc
###
Get http://localhost:3000/api/users/all/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE2LCJpYXQiOjE2Mjc0NzUzMTAsImV4cCI6MTYyNzU2MTcxMH0.SI-Xn83lezSiOH8ZbxLHi_xP-lyLj60ELOVTN1kMNFc
###
Get http://localhost:3000/api/messages/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE2LCJpYXQiOjE2MjczOTQ2NjksImV4cCI6MTYyNzQ4MTA2OX0.T3Gffr4C6d2urtsYthn0uiEduz0e_t9bVgVzjuuBSts
###
Get http://localhost:3000/api/auth/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksImlhdCI6MTYyNjkwNjc0NCwiZXhwIjoxNjI2OTkzMTQ0fQ.drPf7yQJLR1mtAJY_GPJuAKNXOidvhK3mYAhw-70638